# Generated by Django 5.0.2 on 2024-04-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='emaiadress',
            new_name='email',
        ),
    ]
