# Generated by Django 5.0.2 on 2024-04-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregister', '0002_rename_emaiadress_students_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
